name: Scheduled tasks

on:
  schedule:
    - cron:  '13 12 * * *'
  workflow_dispatch:

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'poetry'

      - run: poetry install

      - name: Run Updatecli in Apply mode
        run: poetry run pytest
        env:
          PYTEST_ADDOPTS: ${{ secrets.PYTEST_ADDOPTS }}
